version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es/elasticsearch/data:/usr/share/elasticsearch/data
      - ./es/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - net

  logstash:
    image: logstash
    container_name: logstash
    volumes:
      - ./es/logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./es/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    ports:
      - 5043:5043
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - net
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.2
    container_name: kibana
    volumes:
      - ./es/kibana/config:/usr/share/kibana/config:ro
    ports:
      - 5601:5601
    networks:
      - net
    depends_on:
      - elasticsearch

  debian1:
    image: asampleapp
    container_name: asampleapp
    volumes:
      - ./es/filebeat/config:/etc/filebeat
    command: tail -f /dev/null
    networks:
      - net

  sql:
    image: sql-logging
    container_name: sql-server
    ports:
      - 1433:1433
    networks:
      - net

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1