FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# build runtime image
FROM microsoft/dotnet:2.0-runtime-jessie
WORKDIR /app
COPY --from=build-env /app/out ./

RUN curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.1.3-amd64.deb
RUN dpkg -i filebeat-6.1.3-amd64.deb
# ENTRYPOINT ["dotnet", "ASampleApp.dll"]