FROM docker.elastic.co/logstash/logstash-oss:6.1.2

RUN mkdir -p /opt/logstash/vendor/jar/jdbc/
# && wget https://jdbc.postgresql.org/download/postgresql-9.4.1208.jre7.jar -O /opt/logstash/vendor/jar/jdbc/postgresql-9.4-1208-jdbc41.jar && \ /opt/logstash/bin/plugin install logstash-output-jdbc

COPY sqljdbc_6.0.8112.100_enu.tar.gz /opt/logstash/vendor/jar/jdbc/

RUN gzip -d /opt/logstash/vendor/jar/jdbc/sqljdbc_6.0.8112.100_enu.tar.gz

RUN tar -xf /opt/logstash/vendor/jar/jdbc/sqljdbc_6.0.8112.100_enu.tar -C /opt/logstash/vendor/jar/jdbc
